# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  - name: Run tests
      run: swift test --enable-code-coverage

  - name: Test coverage
    uses: maxep/spm-lcov-action@0.3.0
    with:
        output-file: ./coverage/lcov.info
